# from django.core.exceptions import ValidationError


class CartValidator:
    def __init__(self): ...

    def __call__(self):
        return True


class CartitemValidator:
    def __init__(self): ...

    def __call__(self):
        return True
